# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.5
  - 3.6

install:
  - pip install -U -r requirements_dev.txt
  - python setup.py install

script:
  - py.test

after_success:
  - coverage run --source inicheck -m pytest
  - coveralls

stages:
  - name: deploy
    if:  branch = master OR tag IS present AND repo = USDA-ARS-NWRC/topocalc

deploy:
  provider: pypi
  username: "__token__"
  on:
    tags: true
