# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install: pip install -U -r requirements_dev.txt

script: py.test
